version: "3"

services:
  lago:
    image: getlago/api:latest
    ports:
      - "3001:3000"
    environment:
      DATABASE_URL: postgres://lago:lago@db:5432/lago
      REDIS_URL: redis://redis:6379

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: lago
      POSTGRES_PASSWORD: lago
      POSTGRES_DB: lago

  redis:
    image: redis:7